apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "_.fullname" . }}-setup-rev{{ .Release.Revision }}
  labels:
    {{- include "_.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 3
  activeDeadlineSeconds: 1800
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: psql-setup
          image: postgres:{{ .Values.postgresVersion | default "17" }}
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "_.fullname" . }}-pguser-postgres
                  key: password
          command:
            - /bin/bash
            - -c
            - |
              set -e
              export DB_HOST={{ include "_.fullname" . }}-primary

              echo "Checking for database availability at $DB_HOST..."
              until pg_isready -h "$DB_HOST" -U postgres; do
                echo "Database not ready yet. Sleeping 5s..."
                sleep 5
              done

              {{- range $db := .Values.databases }}
              echo "Setting up database: {{ $db.name }}"

              # Construct the connection string to the primary service
              export DB_HOST={{ include "_.fullname" $ }}-primary

              # Run your specific requirements
              psql -h "$DB_HOST" -U postgres -d "{{ $db.name }}" <<EOF
                ALTER SCHEMA public OWNER TO "{{ $db.name }}";
                ALTER USER "{{ $db.name }}" NOSUPERUSER;
                GRANT ALL ON SCHEMA public TO "{{ $db.name }}";
              EOF
              {{- end }}
