{{- $s3 := lookup "v1" "Secret" .Release.Namespace "chwf-pgo-s3" }}
{{- if $s3 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: objectstorage-creds
  labels:
    {{- include "_.labels" . | nindent 4 }}
type: Opaque
stringData:
  s3.conf: |
    [global]
    repo2-s3-key={{ index $s3.data "access-key" | b64dec }}
    repo2-s3-key-secret={{ index $s3.data "secret-key" | b64dec }}
{{- end }}
