n8n:
  enabled: true
  env:
    WEBHOOK_URL: "https://dev-chwf.apps.gold.devops.gov.bc.ca"
    N8N_SMTP_HOST: "apps.smtp.gov.bc.ca"
    N8N_SMTP_PORT: "25"
    N8N_SMTP_SSL: "false"
    N8N_SMTP_AUTHTYPE: "NONE"
    N8N_SMTP_USER: ""
    N8N_SMTP_PASS: ""
    N8N_SMTP_SENDER: "DoNotReplyCITZ@gov.bc.ca"
    N8N_BASE_URL: https://dev-chwf.apps.gold.devops.gov.bc.ca
    OIDC_ISSUER: https://dev.loginproxy.gov.bc.ca/auth/realms/standard
    EXTERNAL_UI_ENABLED: 'true'
    UI_OIDC_REDIS_PREFIX: "chwf:ui-oidc:dev:"
    AUTHZ_ENVIRONMENT: dev
    CHEFS_BASE_URL: https://chefs-dev.apps.silver.devops.gov.bc.ca
    FEATURES_ENABLED: "workflow-share"

  route:
    enabled: true
    host: dev-chwf.apps.gold.devops.gov.bc.ca

  main:
    env:
      ENABLE_SWAGGER_UI: 'true'

  worker:
    enabled: true

  webhook:
    enabled: true

  runner:
    enabled: true

redis:
  enabled: true

pgo:
  enabled: true

  pgBackRest:
    repos:
      - name: repo1
        retention:
          full: "2"
          fullType: count

        volume:
          volumeClaimSpec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 512Mi
            storageClassName: netapp-file-standard

        schedules:
          full: "0 7 * * 1-5"             # Environment reset/cleanup at 7:00 AM before work starts (Mon-Fri)
          incremental: "0 9-17/2 * * 1-5" # Fast sync every 2 hours during working hours (Mon-Fri)

      - name: repo2
        secretName: chwf-pgo-s3 # pragma: allowlist secret
        retention:
          full: "30"
          fullType: time
        path: /backups/pgo
        uriStyle: path
        s3:
          bucket: workflow-dev
          endpoint: commonservices.objectstore.gov.bc.ca
          region: ca-central-1
        schedules:
          full: "0 7 * * 1-5"             # Environment reset/cleanup at 7:00 AM before work starts (Mon-Fri)
          incremental: "0 9-17/2 * * 1-5" # Fast sync every 2 hours during working hours (Mon-Fri)
backup-storage:
  enabled: true

  image:
    tag: "2.13.0"
    pullPolicy: IfNotPresent

  env:
    S3_BUCKET:
      value: workflow-dev/backups/pgdump/

  backupConfig: |
    postgres=chwf-pgo-replicas:5432/n8n
    postgres=chwf-pgo-replicas:5432/n8n-custom

    */10 * * * * default ./backup.sh -s
    0 7 * * 1-5 default ./backup.sh -s -v all
