n8n:
  enabled: true
  env:
    WEBHOOK_URL: "https://dev-chwf.apps.golddr.devops.gov.bc.ca"
    N8N_SMTP_HOST: "apps.smtp.gov.bc.ca"
    N8N_SMTP_PORT: "25"
    N8N_SMTP_SSL: "false"
    N8N_SMTP_AUTHTYPE: "NONE"
    N8N_SMTP_USER: ""
    N8N_SMTP_PASS: ""
    N8N_SMTP_SENDER: "DoNotReplyCITZ@gov.bc.ca"
    N8N_BASE_URL: https://dev-chwf.apps.golddr.devops.gov.bc.ca
    OIDC_ISSUER: https://dev.loginproxy.gov.bc.ca/auth/realms/standard
    AUTHZ_ENVIRONMENT: dev
    EXTERNAL_UI_ENABLED: 'true'
    UI_OIDC_REDIS_PREFIX: "chwf:ui-oidc:dev:"
    CHEFS_BASE_URL: https://chefs-dev.apps.silver.devops.gov.bc.ca
    FEATURES_ENABLED: "workflow-share"

  route:
    enabled: true
    host: dev-chwf.apps.golddr.devops.gov.bc.ca

  worker:
    enabled: true

  webhook:
    enabled: true

  runner:
    enabled: true

redis:
  enabled: true

pgo:
  enabled: true
  instance:
    dataVolumeClaimSpec:
      resources:
        requests:
          storage: 1.5Gi
  pgBackRest:
  conditionalRestore:
    enabled: true
    s3:
      bucket: workflow-dev/backups/pgdump

# backup-storage is intentionally disabled on GoldDR — backups are created on Gold only
backup-storage:
  enabled: false

dns-probe:
  enabled: true
  env:
    APP_ENV: "dev"
