n8n:
  enabled: true
  env:
    WEBHOOK_URL: "https://workflow.apps.golddr.devops.gov.bc.ca"
    N8N_SMTP_HOST: "apps.smtp.gov.bc.ca"
    N8N_SMTP_PORT: "25"
    N8N_SMTP_SSL: "false"
    N8N_SMTP_AUTHTYPE: "NONE"
    N8N_SMTP_USER: ""
    N8N_SMTP_PASS: ""
    N8N_SMTP_SENDER: "DoNotReplyCITZ@gov.bc.ca"
    N8N_SSRF_PROTECTION_ENABLED: "true"
    N8N_SSRF_ALLOWED_HOSTNAMES: "*.svc.cluster.local"
    N8N_ENV_FEAT_ENCRYPTION_KEY_ROTATION: "true"
    EXECUTIONS_DATA_MAX_AGE: "8784" # 1 year in hours
    N8N_BASE_URL: https://workflow.apps.golddr.devops.gov.bc.ca
    OIDC_ISSUER: https://loginproxy.gov.bc.ca/auth/realms/standard
    CHEFS_GATEWAY_URL: https://submit.digital.gov.bc.ca/app/gateway/v1
    CHEFS_BASE_URL: https://submit.digital.gov.bc.ca
    CSTAR_BASE_URL: https://connect.digital.gov.bc.ca
    FEATURES_ENABLED: "wil, project, workflow-share, tenant-project-sync"
    AUTHZ_ENVIRONMENT: prod

  extraExcludedNodes:
    - "n8n-nodes-base.scheduleTrigger"
    - "n8n-nodes-base.rabbitmqTrigger"
    - "n8n-nodes-base.mqttTrigger"
    - "n8n-nodes-base.amqpTrigger"
    - "n8n-nodes-base.kafkaTrigger"
    - "n8n-nodes-base.redisTrigger"
    - "n8n-nodes-base.emailReadImap"
    - "n8n-nodes-base.rssFeedReadTrigger"
    - "n8n-nodes-base.sseTrigger"
    - "n8n-nodes-base.postgresTrigger"

  route:
    enabled: true
    host: workflow.apps.golddr.devops.gov.bc.ca

  worker:
    enabled: true

  webhook:
    enabled: true

  runner:
    enabled: true

redis:
  enabled: true

pgo:
  enabled: true
  instance:
    dataVolumeClaimSpec:
      resources:
        requests:
          storage: 2Gi
  pgBackRest:

dns-probe:
  enabled: false
  env:
    APP_ENV: "production"
