n8n:
  enabled: true
  env:
    WEBHOOK_URL: https://n8n.developer.gov.bc.ca
    N8N_SMTP_HOST: "apps.smtp.gov.bc.ca"
    N8N_SMTP_PORT: "25"
    N8N_SMTP_SSL: "false"
    N8N_SMTP_AUTHTYPE: "NONE"
    N8N_SMTP_USER: ""
    N8N_SMTP_PASS: ""
    N8N_SMTP_SENDER: "DoNotReplyCITZ@gov.bc.ca"
    N8N_BASE_URL: https://n8n.developer.gov.bc.ca
    OIDC_ISSUER: https://loginproxy.gov.bc.ca/auth/realms/standard
    AUTHZ_ENVIRONMENT: prod
    UI_OIDC_REDIS_PREFIX: "chwf:ui-oidc:prod:"
    CHEFS_BASE_URL: https://submit.digital.gov.bc.ca

  route:
    enabled: true
    host: prod-chwf.apps.golddr.devops.gov.bc.ca

  main:
    deploymentStrategy:
      type: "RollingUpdate"

  worker:
    enabled: true

  webhook:
    enabled: true

  runner:
    enabled: true

redis:
  enabled: true

pgo:
  enabled: true

  instance:
    dataVolumeClaimSpec:
      resources:
        requests:
          storage: 2Gi

  pgBackRest:
  conditionalRestore:
    enabled: false  # enable when dns-probe is enabled for prod-golddr
    s3:
      bucket: workflow-prod/backups/pgdump

# backup-storage is intentionally disabled on GoldDR — backups are created on Gold only
backup-storage:
  enabled: false

dns-probe:
  enabled: false
  env:
    APP_ENV: "production"
