# pnpm-workspace.yaml
packages:
- ./*
allowBuilds:
  '@scarf/scarf': false
  esbuild: false
  eslint-plugin-n8n-nodes-base: false
  isolated-vm: false
  unrs-resolver: false
confirmModulesPurge: false
