replicaCount: 1

image:
  repository: grafana/mimir
  tag: '2.14.0'
  pullPolicy: IfNotPresent

imagePullSecrets: []

podSecurityContext: null  # OpenShift assigns UID from namespace range

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

storage:
  s3:
    insecure: true
    endpoint: ''
    blocksBucket: ''
    alertmanagerBucket: ''
    rulerBucket: ''

extraEnv: []

livenessProbe:
  httpGet:
    path: /ready
    port: http
  initialDelaySeconds: 60
  periodSeconds: 30
  timeoutSeconds: 5

readinessProbe:
  httpGet:
    path: /ready
    port: http
  initialDelaySeconds: 30
  periodSeconds: 15
  timeoutSeconds: 5

resources:
  requests:
    cpu: 10m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
