name: Setup NPM Packages
description: Setup required NPM packages with caching for pnpm
runs:
  using: composite
  steps:
  - name: Setup Tools
    uses: egose/actions/pnpm-packages@68448c0027aeafe0a824f6c9b33fd875e77b844c
    with:
      frozen: 'true'
      ignore-scripts: 'true'
      paths: |
        .
        community-nodes
        external-ui
        external-hooks
        docker-compose/sdg-mock-app
