name: Setup NPM Packages
description: Setup required NPM packages with caching for pnpm
runs:
  using: composite
  steps:
  - name: Setup Tools
    uses: egose/actions/pnpm-packages@e3f0eea78b2bd0b3cfe6b2b9eb6485b000cabfeb
    with:
      frozen: 'true'
      ignore-scripts: 'true'
      paths: |
        .
        community-nodes
        external-ui
        external-hooks
        docker-compose/sdg-mock-app
        doc-site

  - name: Install mermaid-cli
    run: |
      echo "PNPM_HOME=$HOME/.local/share/pnpm" >> "$GITHUB_ENV"
      echo "$HOME/.local/share/pnpm" >> "$GITHUB_PATH"
      export PATH="$HOME/.local/share/pnpm:$PATH"
      pnpm add -g @mermaid-js/mermaid-cli --ignore-scripts
    shell: bash

  - name: Set executable permissions for local format scripts
    run: |
      chmod +x ./.bin/prettier.sh ./.bin/eslint-external-hooks.sh ./.bin/eslint-external-ui.sh ./.bin/commitlint.sh
    shell: bash
