name: Setup NPM Packages
description: Setup required NPM packages with caching for pnpm
runs:
  using: composite
  steps:
  - name: Setup Tools
    uses: egose/actions/pnpm-packages@ef042a54d9446c85fdd1044d342c614b5353f812
    with:
      frozen: 'true'
      ignore-scripts: 'true'
      paths: |
        .
        community-nodes
        external-ui
        external-hooks
        docker-compose/sdg-mock-app

  - name: Set executable permissions for local format scripts
    run: |
      chmod +x ./.bin/prettier.sh ./.bin/eslint-external-hooks.sh ./.bin/eslint-external-ui.sh ./.bin/commitlint.sh
    shell: bash
