{{- if .Values.conditionalRestore.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "_.fullname" . }}-restore-script
  labels:
    {{- include "_.labels" . | nindent 4 }}
data:
  restore.sh: |
    {{- .Files.Get "conditional-restore/restore.sh" | replace "\r" "" | nindent 4 }}
{{- end }}
