volumes:
  n8n_storage:
  postgres_storage:

networks:
  chwf:
    driver: bridge

# REUSABLE ANCHORS
x-common-props: &common-props
  # platform: linux/amd64
  restart: unless-stopped
  networks: [chwf]

x-n8n-env: &n8n-env
  DB_TYPE: postgresdb
  DB_POSTGRESDB_HOST: postgres
  DB_POSTGRESDB_USER: ${POSTGRES_USER}
  DB_POSTGRESDB_PASSWORD: ${POSTGRES_PASSWORD}
  DB_POSTGRESDB_DATABASE: ${POSTGRES_DB:-n8n}
  CUSTOM_DATABASE_URL: postgresql://postgres:postgres@postgres:5432/n8n_custom # pragma: allowlist secret
  N8N_DIAGNOSTICS_ENABLED: 'false'
  N8N_PERSONALIZATION_ENABLED: 'false'
  N8N_TEMPLATES_ENABLED: 'false'
  N8N_AI_ENABLED: 'false'
  N8N_HIRING_BANNER_ENABLED: "false"
  N8N_HIDE_USAGE_PAGE: "true"
  N8N_HIDE_ACTIVATION_ALERT: "true"
  N8N_HIDE_HIDE_GITHUB_STAR_BUTTON: "true"
  N8N_DISABLED_MODULES: "external-secrets,mcp,chat-hub"
  N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
  N8N_USER_MANAGEMENT_JWT_SECRET: ${N8N_USER_MANAGEMENT_JWT_SECRET}
  OLLAMA_HOST: ${OLLAMA_HOST:-ollama:11434}
  N8N_PORT: '5678'
  NODE_ENV: production
  N8N_PROTOCOL: 'http'
  N8N_TRUST_PROXY: 'true'
  N8N_PROXY_HOPS: "1"
  # OIDC
  OIDC_CLIENT_ID: ${OIDC_CLIENT_ID}
  OIDC_CLIENT_SECRET: ${OIDC_CLIENT_SECRET}
  # OIDC_ISSUER_URL: http://keycloak:8080/realms/starter
  OIDC_AUTHORIZATION_ENDPOINT: http://localhost:8080/realms/starter/protocol/openid-connect/auth
  OIDC_TOKEN_ENDPOINT: http://keycloak:8080/realms/starter/protocol/openid-connect/token
  OIDC_USERINFO_ENDPOINT: http://keycloak:8080/realms/starter/protocol/openid-connect/userinfo
  OIDC_REDIRECT_URI: http://localhost:5678/rest/auth/oidc/callback
  OIDC_ROLES_CLAIM: client_roles
  N8N_ADDITIONAL_NON_UI_ROUTES: auth
  # For custom nodes
  DEVX_CONNECTOR_API_URL: ${DEVX_CONNECTOR_API_URL}
  DEVX_CONNECTOR_API_KEY: ${DEVX_CONNECTOR_API_KEY}
  # internal auth token for secure communication between n8n and external hooks
  INTERNAL_AUTH_TOKEN: ${INTERNAL_AUTH_TOKEN}

services:
  adaptivecard:
    <<: *common-props
    container_name: adaptivecard
    build:
      context: ./adaptivecard
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    <<: *common-props
    container_name: postgres
    image: postgres:18.0-alpine3.22
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres_storage:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10

  keycloak:
    <<: *common-props
    container_name: keycloak
    build:
      context: ./keycloak
      dockerfile: Dockerfile
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_URL_PORT: 5432
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_HOSTNAME_STRICT: 'false'
      KC_HEALTH_ENABLED: 'true'
      KC_METRICS_ENABLED: 'true'
      KC_HOSTNAME_STRICT_HTTPS: 'false'
      KC_HTTP_ENABLED: 'true'
      KC_HTTP_PORT: 8080
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/conf/server.crt.pem
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/conf/server.key.pem
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      JAVA_OPTS_APPEND: -Dkeycloak.profile.feature.scripts=enabled
    ports:
      - '8080:8080'
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/health/live']
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak-provision:
    <<: *common-props
    container_name: keycloak-provision
    restart: 'no' # Should only run once
    build: ./keycloak-provision
    environment:
      KEYCLOAK_URL: http://keycloak:8080
      MASTER_ADMIN: ${KEYCLOAK_ADMIN}
      MASTER_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      AUTH_REALM_NAME: starter
      AUTH_CLIENT_ID: ${OIDC_CLIENT_ID}
      AUTH_CLIENT_SECRET: ${OIDC_CLIENT_SECRET}
    depends_on:
      keycloak:
        condition: service_started

  n8n-provision:
    <<: *common-props
    container_name: n8n-provision
    restart: 'no'
    build:
      context: ..
      dockerfile: Dockerfile
    environment: *n8n-env
    volumes:
      - n8n_storage:/home/node/.n8n
      - ./n8n/demo-data:/demo-data
    entrypoint: /bin/sh
    command: >
      -c "if [ -z \"$$(n8n list:workflow --onlyId)\" ]; then
            n8n import:credentials --separate --input=/demo-data/credentials &&
            n8n import:workflow --separate --input=/demo-data/workflows;
          fi;

          echo 'Installing community nodes';
          mkdir -p /home/node/.n8n/nodes;
          cd /home/node/.n8n/nodes && npm install /community-nodes;

          echo 'Installing external hooks';
          cd /external-hooks && node migrate.cjs;

          echo 'n8n provision completed!';
          "
    depends_on:
      postgres:
        condition: service_healthy

  n8n:
    <<: *common-props
    container_name: n8n
    build:
      context: ..
      dockerfile: Dockerfile
    environment: *n8n-env
    ports:
      - '5678:5678'
    volumes:
      - n8n_storage:/home/node/.n8n
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_started
      n8n-provision:
        condition: service_completed_successfully
