{{- if and .Values.grafana.enabled .Values.grafanaRoute.enabled .Values.grafanaRoute.host }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "_.fullname" . }}-grafana
  labels:
    {{- include "_.labels" . | nindent 4 }}
  annotations:
    haproxy.router.openshift.io/balance: roundrobin
    haproxy.router.openshift.io/timeout: 600s
spec:
  host: {{ .Values.grafanaRoute.host }}
  port:
    targetPort: service
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ include "_.fullname" . }}-grafana
{{- end }}
