data:
  template.rocketchat-on-created: |
    webhook:
      rocketchat-on-created:
        method: POST
        path: /hooks/{{.app.metadata.annotations.rocketchatWebhookToken}}
        body: |
          {
            "text":"Argo CD Application `{{.app.metadata.name}}` has been created - https://gitops-shared.apps.klab.devops.gov.bc.ca/applications/{{.app.metadata.name}}"
          }
  template.rocketchat-on-degraded: |
    webhook:
      rocketchat-on-degraded:
        method: POST
        path: /hooks/{{.app.metadata.annotations.rocketchatWebhookToken}}
        body: |
          {
            "text":"Argo CD Application `{{.app.metadata.name}}` is in a degreaded state - https://gitops-shared.apps.klab.devops.gov.bc.ca/applications/{{.app.metadata.name}}"
          }
  template.rocketchat-on-deleted: |
    webhook:
      rocketchat-on-deleted:
        method: POST
        path: /hooks/{{.app.metadata.annotations.rocketchatWebhookToken}}
        body: |
          {
            "text":"Argo CD Application `{{.app.metadata.name}}` has been deleted - https://gitops-shared.apps.klab.devops.gov.bc.ca/applications/"
          }
  template.rocketchat-on-deployed: |
    webhook:
      rocketchat-on-deployed:
        method: POST
        path: /hooks/{{.app.metadata.annotations.rocketchatWebhookToken}}
        body: |
          {
            "text":"Argo CD Application `{{.app.metadata.name}}` has been deployed - https://gitops-shared.apps.klab.devops.gov.bc.ca/applications/{{.app.metadata.name}}"
          }
  template.rocketchat-on-out-of-sync: |
    webhook:
      rocketchat-on-out-of-sync:
        method: POST
        path: /hooks/{{.app.metadata.annotations.rocketchatWebhookToken}}
        body: |
          {
            "text":"The klab application `{{.app.metadata.name}}` is out of sync - https://gitops-shared.apps.klab.devops.gov.bc.ca/applications/{{.app.metadata.name}}?node=argoproj.io%2FApplication%2F{{.app.metadata.namespace}}%2F{{.app.metadata.name}}%2F0&tab=diff"
          }
  template.rocketchat-on-out-of-sync-long: |
    webhook:
      rocketchat-on-out-of-sync-long:
        method: POST
        path: /hooks/{{.app.metadata.annotations.rocketchatWebhookToken}}
        body: |
          {
            "text":"The klab application `{{.app.metadata.name}}` is out of sync - https://gitops-shared.apps.klab.devops.gov.bc.ca/applications/{{.app.metadata.name}}?node=argoproj.io%2FApplication%2F{{.app.metadata.namespace}}%2F{{.app.metadata.name}}%2F0&tab=diff"
          }
  template.rocketchat-on-sync-running: |
    webhook:
      rocketchat-on-sync-running:
        method: POST
        path: /hooks/{{.app.metadata.annotations.rocketchatWebhookToken}}
        body: |
          {
            "text":"The sync operation of application `{{.app.metadata.name}}` is running - https://gitops-shared.apps.klab.devops.gov.bc.ca/applications/{{.app.metadata.name}}?operation=true"
          }
  template.rocketchat-on-sync-status-unknown: |
    webhook:
      rocketchat-on-sync-status-unknown:
        method: POST
        path: /hooks/{{.app.metadata.annotations.rocketchatWebhookToken}}
        body: |
          {
            "text":"The sync status of application `{{.app.metadata.name}}` is unknown - https://gitops-shared.apps.klab.devops.gov.bc.ca/applications/{{.app.metadata.name}}?operation=true"
          }
  template.rocketchat-on-sync-succeeded: |
    webhook:
      rocketchat-on-sync-succeeded:
        method: POST
        path: /hooks/{{.app.metadata.annotations.rocketchatWebhookToken}}
        body: |
          {
            "text":"The sync status of application `{{.app.metadata.name}}` has succeeded - https://gitops-shared.apps.klab.devops.gov.bc.ca/applications/{{.app.metadata.name}}?operation=true"
          }
  template.rocketchat-sync-failure: |
    webhook:
      rocketchat-sync-failure:
        method: POST
        path: /hooks/{{.app.metadata.annotations.rocketchatWebhookToken}}
        body: |
          {
            "text":"Argo CD sync failure for `{{.app.metadata.name}}` at {{.app.status.operationState.finishedAt}} - https://gitops-shared.apps.klab.devops.gov.bc.ca/applications/{{.app.metadata.name}}?operation=true"
          }
