{{- if .Values.alloy.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "_.fullname" . }}-alloy-config
  labels:
    {{- include "_.labels" . | nindent 4 }}
data:
  config.alloy: |
    {{- .Files.Get "alloy/config.alloy" | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "_.fullname" . }}-alloy-env
  labels:
    {{- include "_.labels" . | nindent 4 }}
data:
  ALLOY_N8N_ADDRESS: "{{ include "_.fullname" . }}-n8n-main:5678"
  ALLOY_MIMIR_URL: "http://{{ include "_.fullname" . }}-mimir:8080/api/v1/push"
  ALLOY_TEMPO_URL: "{{ include "_.fullname" . }}-tempo:4317"
  ALLOY_LOKI_URL: "http://{{ include "_.fullname" . }}-loki:3100/loki/api/v1/push"
{{- end }}
