apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "_sdg.fullname" . }}
  labels:
    {{- include "_sdg.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: netapp-file-standard
