name: Setup Tools
description: Setup required tools in the workspace

runs:
  using: composite
  steps:
  - name: Setup Tools
    uses: egose/actions/asdf-tools@e3f0eea78b2bd0b3cfe6b2b9eb6485b000cabfeb

  - name: Install python tools
    run: |
      pip install -r requirements.txt
      asdf reshim
    shell: bash
