name: Reusable Build and Push

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      docker-path:
        required: true
        type: string
      metadata-tags:
        required: false
        type: string
        default: |
          type=ref,event=branch
          type=sha,format=long,prefix=,suffix=

env:
  GITHUB_REGISTRY: ghcr.io

permissions:
  contents: read
  actions: read
  packages: write
  security-events: write

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

    - name: Setup Tools
      uses: ./.github/actions/setup-tools

    - name: Build and Push
      uses: egose/actions/docker-build-push@ef042a54d9446c85fdd1044d342c614b5353f812
      with:
        registry-url: ${{ env.GITHUB_REGISTRY }}
        registry-username: ${{ github.actor }}
        registry-password: ${{ secrets.GITHUB_TOKEN }}
        image-name: ${{ inputs.image-name }}
        docker-context: ${{ inputs.docker-path }}
        docker-file: ${{ inputs.docker-path }}/Dockerfile
        docker-outputs: type=image,push=true,compression=gzip,force-compression=true
        metadata-tags: ${{ inputs.metadata-tags }}
        trivy: false
