name: Deploy DevX

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Image tag to deploy
        required: false
        type: string
        default: latest
      environment:
        description: Deployment environment
        required: true
        type: choice # Defines the input as a dropdown menu
        default: dev
        options: # List of allowed values
        - dev
        - test
        - prod
  workflow_call:
    inputs:
      tag:
        description: Image tag to deploy
        required: false
        type: string
        default: main
      environment:
        description: Deployment environment
        required: true
        type: string
        default: dev

permissions:
  contents: read

jobs:
  deploy-devx:
    name: Deploy DevX-${{ inputs.environment }}
    uses: ./.github/workflows/deploy.yml
    secrets: inherit # pragma: allowlist secret
    with:
      environment: devx-${{ inputs.environment }}
      tag: ${{ github.sha }}

  deploy-devx-dr:
    name: Deploy DevX-${{ inputs.environment }}dr
    uses: ./.github/workflows/deploy.yml
    secrets: inherit # pragma: allowlist secret
    with:
      environment: devx-${{ inputs.environment }}dr
      tag: ${{ github.sha }}
