name: Publish Documentation

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - docs/**
    - doc-site/**

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  publish:
    name: Publish
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      with:
        fetch-depth: 0

    - name: Setup Tools
      uses: ./.github/actions/setup-tools

    - name: Setup NPM Packages
      uses: ./.github/actions/setup-npm

    - run: pnpm build
      working-directory: doc-site
      env:
        DOCS_URL: https://bcgov.github.io
        DOCS_BASE_URL: /common-hosted-workflow/

    - name: Deploy to gh-pages branch
      uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./doc-site/build
        publish_branch: gh-pages
        keep_files: true
