name: Deploy SDG

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Image tag to deploy
        required: false
        type: string
        default: latest
      environment:
        description: Deployment environment
        required: true
        type: choice # Defines the input as a dropdown menu
        default: dev
        options: # List of allowed values
        - dev
        - test
        - prod
  workflow_call:
    inputs:
      tag:
        description: Image tag to deploy
        required: false
        type: string
        default: main
      environment:
        description: Deployment environment
        required: true
        type: string
        default: dev
    secrets:
      OPENSHIFT_SERVER:
        required: true
      OPENSHIFT_TOKEN:
        required: true

permissions:
  contents: read

jobs:
  deploy-sdg:
    name: Deploy SDG-${{ inputs.environment }}
    uses: ./.github/workflows/_deploy.yml
    secrets:
      OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
      OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
    with:
      environment: sdg-${{ inputs.environment }}
      tag: ${{ inputs.tag }}

  deploy-sdg-dr:
    name: Deploy SDG-${{ inputs.environment }}dr
    uses: ./.github/workflows/_deploy.yml
    secrets:
      OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
      OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
    with:
      environment: sdg-${{ inputs.environment }}dr
      tag: ${{ inputs.tag }}
