name: Sync Docs to Confluence

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - docs/**
    - .github/workflows/docs-to-confluence.yml

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  docs-as-code:
    runs-on: ubuntu-latest
    environment: confluence
    steps:
    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

    - name: Setup Tools
      uses: ./.github/actions/setup-tools

    - name: Sync Docs to Confluence
      uses: egose/actions/confluence@dfe5d14c69e654ca87d9f6fc491084a59eed6181
      with:
        folder: docs
        username: ${{ secrets.CONFLUENCE_USERNAME }}
        api-token: ${{ secrets.CONFLUENCE_API_TOKEN }}
        confluence-base-url: ${{ vars.CONFLUENCE_BASE_URL }}
        space-key: ${{ vars.CONFLUENCE_SPACE_KEY }}
        parent-page-id: ${{ vars.CONFLUENCE_PARENT_PAGE_ID }}
