name: Merge

on:
  push:
    branches:
    - main
    paths-ignore:
    - workflows/merge.yml
    - docs/**
    - terraform/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: read
  packages: write
  security-events: write

jobs:
  build-push-n8n:
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: bcgov/chwf
      docker-path: .
    secrets: inherit # pragma: allowlist secret

  build-push-adaptivecard:
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: bcgov/chwf-adaptivecard
      docker-path: docker-compose/adaptivecard
    secrets: inherit # pragma: allowlist secret

  build-push-sdg-mock-app:
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: bcgov/chwf-sdg-mock-app
      docker-path: docker-compose/sdg-mock-app
    secrets: inherit # pragma: allowlist secret

  deploy-devx-dev:
    name: Deploys DevX (Dev)
    uses: ./.github/workflows/deploy-devx.yml
    needs: [build-push-n8n]
    secrets: inherit # pragma: allowlist secret
    with:
      environment: dev
      tag: ${{ github.sha }}

  deploy-sdg-dev:
    name: Deploys SDG (Dev)
    uses: ./.github/workflows/deploy-sdg.yml
    needs: [build-push-n8n, build-push-sdg-mock-app]
    secrets: inherit # pragma: allowlist secret
    with:
      environment: dev
      tag: ${{ github.sha }}
