name: Run unit tests

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    steps:
    - uses: hmarr/debug-action@f7318c783045ac39ed9bb497e22ce835fdafbfe6
    - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493

    - name: Setup Tools
      uses: ./.github/actions/setup-tools

    - name: Setup NPM Packages
      uses: ./.github/actions/setup-npm

    - name: Test community nodes build & test
      run: |
        pnpm build
        pnpm test
      working-directory: ./community-nodes
      shell: bash

    - name: Test adaptivecard sample app build & lint
      run: |
        pnpm build
        pnpm lint
      working-directory: ./docker-compose/adaptivecard
      shell: bash

    - name: Test sdg-mock-app sample app build & lint
      run: |
        pnpm build
        pnpm lint
      working-directory: ./docker-compose/sdg-mock-app
      shell: bash

    - name: Test external-hooks build & test
      run: |
        pnpm bundle
        pnpm test
      working-directory: ./external-hooks
      shell: bash
