name: OWASP ZAP Scan

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: Target URL to scan
        required: true
        type: choice
        default: https://test-chwf.apps.gold.devops.gov.bc.ca
        options:
        - https://dev-chwf.apps.gold.devops.gov.bc.ca
        - https://test-chwf.apps.gold.devops.gov.bc.ca
        - https://n8n.developer.gov.bc.ca
      scan_ui_path:
        description: Scan /ui path only
        required: false
        type: choice
        default: no
        options:
        - no
        - yes

permissions:
  contents: read
  issues: write

jobs:
  zap-scan:
    name: ZAP Full Scan
    runs-on: ubuntu-latest
    steps:
    - name: ZAP Full Scan
      uses: zaproxy/action-full-scan@3c58388149901b9a03b7718852c5ba889646c27c# v0.12.0
      with:
        target: ${{ inputs.scan_ui_path == 'yes' && format('{0}/ui', inputs.target_url) || inputs.target_url }}
        issue_title: ZAP Scan - ${{ inputs.scan_ui_path == 'yes' && format('{0}/ui', inputs.target_url) || inputs.target_url }}
        cmd_options: ${{ inputs.scan_ui_path == 'yes' && '-config globalexcludeurl.url.regex="^((?!/ui).)*$"' || '' }}
        fail_action: false
        artifact_name: zap_scan_report
